config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :users
  resources :feeds
  post '/feeds/:user_id_for/', to: 'feeds#feed_post'
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :keijibans do
    resources :responses, only: [:create, :destroy]
  end

end

app/models/keijiban.rb
class Keijiban < ActiveRecord::Base
  has_many :responses
  has_many :users
  default_scope -> { order('updated_at DESC') }
end

app/controllers/keijibans_controller.rb
class KeijibansController < ApplicationController
  before_action :signed_in_user
  def index
    @keijibans = Keijiban.all
  end

  def show
    @keijiban = Keijiban.find(params[:id])
    @responses = @keijiban.responses
    #@responses.user_id = @current_user.id
  end

  def new
    @keijiban = Keijiban.new
  end

  def create
    @keijiban = Keijiban.new(keijiban_params)
    @keijiban.save
    redirect_to keijibans_path
  end

  private
  def keijiban_params
   params[:keijiban].permit(:title)
  end


  # Before actions

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  end

app/helpers/keijibans_helper.rb
module KeijibansHelper
end

app/views/keijibans/index.html.erb
<h1>掲示板</h1>
<p><%= link_to "スレをつくる", new_keijiban_path %></p>
<br>
<ul>
  <% @keijibans.each do |keijiban| %>
  <li><%= link_to keijiban.title, keijiban_path(keijiban.id) %></li>
  <% end %>

</ul>

app/views/keijibans/new.html.erb
<h1>掲示板を作りましょう</h1>
<%= form_for @keijiban do |k| %>
    <p>
      <%= k.label :title %> <br>
      <%= k.text_area :title %>

    </p>

    <p>
      <%= k.submit %>
    </p>

<% end %>

app/views/keijibans/show.html.erb
<h1><%= @keijiban.title %></h1>
<div class="row">
<aside class="span4">
<%= form_for [@keijiban, @keijiban.responses.build] do |f| %>
    <%= f.label :ID %><br>
    <%= f.text_field :user_id %><br>
    <%= f.label :name %> <br>
    <%= f.text_field :name %> <br>
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.submit %>
    <% end %>
  </aside>

<% @responses.each do |response| %>

    <%if response%>
<!---
    <%# link_to User.find(response.user_id).name, "/users/show/#{response.user_id}"%>
-->   <%= response.user_id %>
      <%= link_to response.name, "/users/#{response.user_id}"%><br>
      <%# response.user_id %>
      <%# response.name %>
      <%= response.content %><br>
      <%end%>

<% end %>

</div>